name: Trivy Security Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  security-scan:
    uses: Moonlet/organization-workflows/.github/workflows/trivy-scan.yml@v1-trivy-scan
